#!/usr/bin/env bash

set -eo pipefail

vimdir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site"

mkdir -p "$vimdir/autoload"
curl -fLo "$vimdir/autoload/plug.vim" \
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

nvim +PlugInstall +qall
